name: Build & Publish Debug APK

on:
 push:
  branches:
   - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: add keystore from base64
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore
    - name: keystore pass
      run: export KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}"
    - name: key alias
      run: export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
    - name: key pass
      run: export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: run gradlew
      run: ./gradlew assembleRelease
    - name: Get apk path
      id: apk-path
      run: |
        path=$(find **/build/outputs/apk -name '*.apk' -type f | head -1)
        echo "::set-output name=path::$path"
    - name: Upload apk file
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: ${{ steps.apk-path.outputs.path }}
